# Generated by Django 4.2.1 on 2023-07-07 17:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projetos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projeto",
            old_name="description",
            new_name="descricao",
        ),
        migrations.RenameField(
            model_name="projeto",
            old_name="done",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="projeto",
            old_name="title",
            new_name="titulo",
        ),
    ]
