# Generated by Django 4.2.1 on 2023-07-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projetos", "0002_rename_description_projeto_descricao_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projeto",
            old_name="descricao",
            new_name="descriçao",
        ),
        migrations.AlterField(
            model_name="projeto",
            name="status",
            field=models.CharField(
                choices=[("fazendo", "Fazendo"), ("feito", "Feito")], max_length=10
            ),
        ),
    ]
