# Generated by Django 4.2.1 on 2023-07-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projetos", "0003_rename_descricao_projeto_descriçao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="status",
            field=models.CharField(
                choices=[
                    ("fazendo", "Fazendo"),
                    ("feito", "Feito"),
                    ("fazer", "Fazer"),
                ],
                max_length=10,
            ),
        ),
    ]
