# Generated by Django 4.2.1 on 2023-09-15 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projetos", "0005_alter_projeto_descriçao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projeto",
            name="status",
        ),
    ]
