# Generated by Django 4.2.1 on 2023-09-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[
                    ("backlog", "Backlog"),
                    ("to do", "To do"),
                    ("doing", "Doing"),
                    ("done", "Done"),
                ],
                max_length=10,
            ),
        ),
    ]
