# Generated by Django 4.2.5 on 2023-09-28 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0004_todo_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="user",
        ),
    ]
